### ISSUE TITLE
After installation Arcadia doesn't run

### ISSUE THREAD

**Issue by ghost** [angal/arcadia#60]
Hello! I hope anyone will answer. I installed Arcadia, but when I try to run it from command line, it returns me `bash: unknown command 'arcadia'`. I'm using Linux Mint 17. Thanks!
P.S.
Installed it by running `$ gem install arcadia`, then tried to run it `$ arcadia`

**Comment by angal** [comment]
Hi,
probably you have to install arcadia  with sudo (sudo gem install arcadia),
because gem must copy "arcadia" executable into write protected directory as "/usr/bin/", so you can find it when execute from command line.

**Comment by ghost** [comment]
thank you, I've already solved the problem! I had some problems with Ruby
installed itself, so I reinstalled it totally and then installed Arcadia.
now I can't figure out how to install tk, here's my question on stack
overflow
http://stackoverflow.com/questions/37237089/ruby-tk-installation-in-rbenv-in-linux-mint-17-qiana

2016-05-16 1:19 GMT+03:00 Antonio notifications@github.com:

**Comment by maxie7** [comment]
1st step:
sudo gem install arcadia
[sudo] password for max: 
Fetching: coderay-1.1.1.gem (100%)
Successfully installed coderay-1.1.1
Fetching: arcadia-1.1.1.gem (100%)
Successfully installed arcadia-1.1.1
Parsing documentation for arcadia-1.1.1
Installing ri documentation for arcadia-1.1.1
invalid options: -SNw2
(invalid options are ignored)
Parsing documentation for coderay-1.1.1
Installing ri documentation for coderay-1.1.1
Done installing documentation for arcadia, coderay after 41 seconds
2 gems installed

2nd step (trying to launch arcadia):
arcadia
/usr/lib/ruby/2.1.0/rubygems/dependency.rb:298:in `to_specs': Could not find 'arcadia' (>= 0) among 153 total gem(s) (Gem::LoadError)
    from /usr/lib/ruby/2.1.0/rubygems/dependency.rb:309:in`to_spec'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:53:in `gem'
    from /usr/local/bin/arcadia:22:in`<main>'

My OS is Debian Jessie 8.5
What shall i do?
